name: "AI Code Review Action"
description: "Perform code reviews and comment on diffs using OpenAI API."
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  MODEL_PROVIDER:
    description: "Model provider."
    required: true
  AI_MODEL:
    description: "AI model name"
    required: true
  OPENAI_API_KEY:
    description: "OpenAI API key for GPT."
    required: false
  ANTHROPIC_API_KEY:
    description: "Anthropic API key for Claude."
    required: false
  MAX_OUTPUT_TOKENS:
    description: "Maximum tokens for the code review."
    required: false
    default: 4096
  MAX_CONTEXT_TOKENS:
    description: "Maximum tokens for the context."
    required: false
    default: 16384
  PROMPT_ADDITIONAL_REQUIREMENTS:
    description: "Additional requirements for the code review."
    required: false
  IGNORE_PATTERNS:
    description: "Glob patterns to exclude files from the diff analysis"
    required: false
    default: ""
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "aperture"
  color: "green"
